CREATE TABLE "USUARIO" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "nome" VARCHAR(150) NOT NULL,
    "email" VARCHAR(150) NOT NULL,
    "senha" VARCHAR(255) NOT NULL,
    "ativo" BOOLEAN NOT NULL,
    "data_criacao" TIMESTAMP(6) NOT NULL,

    CONSTRAINT "USUARIO_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ORGANIZACAO" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "nome" VARCHAR(150) NOT NULL,
    "descricao" TEXT NOT NULL,
    "inicio_gestao" DATE NOT NULL,
    "fim_gestao" DATE NOT NULL,
    "link_publico" VARCHAR(255),
    "transparencia_ativa" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "ORGANIZACAO_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "MEMBRO" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" BIGINT NOT NULL,
    "organizacao_id" BIGINT NOT NULL,
    "papel" VARCHAR(20) NOT NULL,
    "data_vinculo" DATE NOT NULL,
    "ativo" BOOLEAN NOT NULL,

    CONSTRAINT "MEMBRO_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "MEMBRO_papel_check" CHECK ("papel" IN ('TESOUREIRO', 'CONSULTOR'))
);

CREATE TABLE "CATEGORIA" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "organizacao_id" BIGINT NOT NULL,
    "nome" VARCHAR(100) NOT NULL,
    "descricao" TEXT NOT NULL,
    "tipo" VARCHAR(20) NOT NULL,
    "ativa" BOOLEAN NOT NULL,

    CONSTRAINT "CATEGORIA_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "CATEGORIA_tipo_check" CHECK ("tipo" IN ('ENTRADA', 'SAIDA'))
);

CREATE TABLE "LANCAMENTO" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "organizacao_id" BIGINT NOT NULL,
    "usuario_id" BIGINT NOT NULL,
    "categoria_id" BIGINT NOT NULL,
    "valor" DECIMAL(12,2) NOT NULL,
    "data" DATE NOT NULL,
    "tipo" VARCHAR(20) NOT NULL,
    "descricao" TEXT NOT NULL,
    "origem" VARCHAR(150),
    "destinatario" VARCHAR(150),
    "status" VARCHAR(20) NOT NULL,
    "data_criacao" TIMESTAMP(6) NOT NULL,
    "data_estorno" TIMESTAMP(6),

    CONSTRAINT "LANCAMENTO_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "LANCAMENTO_valor_check" CHECK ("valor" > 0),
    CONSTRAINT "LANCAMENTO_tipo_check" CHECK ("tipo" IN ('ENTRADA', 'SAIDA')),
    CONSTRAINT "LANCAMENTO_status_check" CHECK ("status" IN ('ATIVO', 'ESTORNADO'))
);

CREATE TABLE "COMPROVANTE" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "lancamento_id" BIGINT NOT NULL,
    "nome_arquivo" VARCHAR(255) NOT NULL,
    "tipo_arquivo" VARCHAR(50) NOT NULL,
    "tamanho" BIGINT NOT NULL,
    "url_arquivo" VARCHAR(500) NOT NULL,
    "data_upload" TIMESTAMP(6) NOT NULL,

    CONSTRAINT "COMPROVANTE_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "META" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "organizacao_id" BIGINT NOT NULL,
    "descricao" VARCHAR(255) NOT NULL,
    "valor_alvo" DECIMAL(12,2) NOT NULL,
    "prazo" DATE NOT NULL,
    "data_criacao" TIMESTAMP(6) NOT NULL,

    CONSTRAINT "META_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "USUARIO_email_key" ON "USUARIO"("email");
CREATE UNIQUE INDEX "ORGANIZACAO_link_publico_key" ON "ORGANIZACAO"("link_publico");
CREATE UNIQUE INDEX "MEMBRO_usuario_id_organizacao_id_key" ON "MEMBRO"("usuario_id", "organizacao_id");
CREATE INDEX "MEMBRO_organizacao_id_idx" ON "MEMBRO"("organizacao_id");
CREATE UNIQUE INDEX "CATEGORIA_organizacao_id_nome_tipo_key" ON "CATEGORIA"("organizacao_id", "nome", "tipo");
CREATE INDEX "LANCAMENTO_organizacao_id_data_idx" ON "LANCAMENTO"("organizacao_id", "data");
CREATE INDEX "LANCAMENTO_organizacao_id_categoria_id_idx" ON "LANCAMENTO"("organizacao_id", "categoria_id");
CREATE INDEX "LANCAMENTO_organizacao_id_status_idx" ON "LANCAMENTO"("organizacao_id", "status");
CREATE INDEX "LANCAMENTO_usuario_id_idx" ON "LANCAMENTO"("usuario_id");
CREATE INDEX "LANCAMENTO_categoria_id_idx" ON "LANCAMENTO"("categoria_id");
CREATE UNIQUE INDEX "COMPROVANTE_lancamento_id_key" ON "COMPROVANTE"("lancamento_id");
CREATE INDEX "META_organizacao_id_idx" ON "META"("organizacao_id");

ALTER TABLE "MEMBRO" ADD CONSTRAINT "MEMBRO_usuario_id_fkey"
    FOREIGN KEY ("usuario_id") REFERENCES "USUARIO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MEMBRO" ADD CONSTRAINT "MEMBRO_organizacao_id_fkey"
    FOREIGN KEY ("organizacao_id") REFERENCES "ORGANIZACAO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CATEGORIA" ADD CONSTRAINT "CATEGORIA_organizacao_id_fkey"
    FOREIGN KEY ("organizacao_id") REFERENCES "ORGANIZACAO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LANCAMENTO" ADD CONSTRAINT "LANCAMENTO_organizacao_id_fkey"
    FOREIGN KEY ("organizacao_id") REFERENCES "ORGANIZACAO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LANCAMENTO" ADD CONSTRAINT "LANCAMENTO_usuario_id_fkey"
    FOREIGN KEY ("usuario_id") REFERENCES "USUARIO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LANCAMENTO" ADD CONSTRAINT "LANCAMENTO_categoria_id_fkey"
    FOREIGN KEY ("categoria_id") REFERENCES "CATEGORIA"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "COMPROVANTE" ADD CONSTRAINT "COMPROVANTE_lancamento_id_fkey"
    FOREIGN KEY ("lancamento_id") REFERENCES "LANCAMENTO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "META" ADD CONSTRAINT "META_organizacao_id_fkey"
    FOREIGN KEY ("organizacao_id") REFERENCES "ORGANIZACAO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
